### ISSUE TITLE
Problems Faced

### ISSUE THREAD

**Issue by WOW-Reborn** [mindsear/CustomXP-LootRates#1]
I have a few issues.  I patched it line by line since the .patch file is out of date, but there are a few things that are strange.  First its not seting a default xp rate.  Users should automatically be 1x instead they are 0x on xp until they do .rate xp 1.  New users to the server don't understand what is going on and it causes issues.  Secondly if I disable Loot levels and leave xp levels on it says loot is 0 and xp isn't working.  Either the trinitycore changed and messed it up or I'm not tech savy enough to solve the issue.

**Comment by mindsear** [comment]
I will try to update it if I can.
